### ISSUE TITLE
Build Errors

### ISSUE THREAD

**Issue by FM-500** [martgras/LukeRobertsControl#1]
Hello, it's michael287 from Loxforum,

I was trying to build the project, but getting errors, which I can't make any sense of:

> Building in release mode
Compiling .pio\build\esp32dev\src\LukeRobertsBle.cpp.o
Compiling .pio\build\esp32dev\src\app_utils.cpp.o
Compiling .pio\build\esp32dev\src\main.cpp.o
Compiling .pio\build\esp32dev\src\rotaryencoder.cpp.o
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Users\freyl\.platformio\python3\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Users\freyl\.platformio\python3\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\freyl\.platformio\penv\lib\site-packages\platformio\proc.py", line 46, in run
    self.do_reading()
  File "c:\users\freyl\.platformio\penv\lib\site-packages\platformio\proc.py", line 99, in do_reading
    for line in iter(self._pipe_reader.readline, ""):
  File "C:\Users\freyl\.platformio\python3\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 170: character maps to <undefined>
 
========================= [FAILED] Took 10.99 seconds =========================

Any ideas?

**Comment by martgras** [comment]
Compile error only happened when using Atom. No repro with Vscode
